repos:
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        types: [c++, c]
        files: \.(cpp|h|ino)$
        args: [-i]
-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black
        language_version: python3
        types: [python]
        args: [--line-length=100]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
